CREATE TABLE IF NOT EXISTS `#__xdecarophotos_photos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_component` VARCHAR(128) NOT NULL,
  `owner_entity` VARCHAR(64) NOT NULL,
  `owner_id` VARCHAR(128) NOT NULL,
  `context_component` VARCHAR(128) NULL,
  `context_entity` VARCHAR(64) NULL,
  `context_id` VARCHAR(128) NULL,
  `photo_type` VARCHAR(32) NOT NULL DEFAULT 'original',
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL,
  `original_path` VARCHAR(512) NOT NULL,
  `mime_type` VARCHAR(64) NOT NULL,
  `width` INT UNSIGNED NOT NULL DEFAULT 0,
  `height` INT UNSIGNED NOT NULL DEFAULT 0,
  `file_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `orientation` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `season` VARCHAR(32) NULL,
  `created` DATETIME NOT NULL,
  `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL,
  `modified_by` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_owner` (`owner_component`, `owner_entity`, `owner_id`),
  INDEX `idx_context` (`context_component`, `context_entity`, `context_id`),
  INDEX `idx_photo_type` (`photo_type`),
  INDEX `idx_status` (`status`),
  INDEX `idx_primary` (`is_primary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__xdecarophotos_variants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` INT UNSIGNED NOT NULL,
  `preset` VARCHAR(32) NOT NULL,
  `path` VARCHAR(512) NOT NULL,
  `mime_type` VARCHAR(64) NOT NULL,
  `width` INT UNSIGNED NOT NULL DEFAULT 0,
  `height` INT UNSIGNED NOT NULL DEFAULT 0,
  `crop_x` DECIMAL(12,4) NOT NULL DEFAULT 0,
  `crop_y` DECIMAL(12,4) NOT NULL DEFAULT 0,
  `crop_width` DECIMAL(12,4) NOT NULL DEFAULT 0,
  `crop_height` DECIMAL(12,4) NOT NULL DEFAULT 0,
  `rotation` SMALLINT NOT NULL DEFAULT 0,
  `generated` DATETIME NOT NULL,
  `checksum` CHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_variant_photo_id` (`photo_id`),
  INDEX `idx_variant_preset` (`preset`),
  CONSTRAINT `fk_xdecarophotos_variant_photo` FOREIGN KEY (`photo_id`) REFERENCES `#__xdecarophotos_photos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
