CREATE TABLE IF NOT EXISTS `#__xdecarophotos_photos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_component` VARCHAR(190) NOT NULL,
  `owner_entity` VARCHAR(100) NOT NULL,
  `owner_id` VARCHAR(190) NOT NULL,
  `context_component` VARCHAR(190) NULL,
  `context_entity` VARCHAR(100) NULL,
  `context_id` VARCHAR(190) NULL,
  `photo_type` VARCHAR(50) NOT NULL DEFAULT 'original',
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `original_path` VARCHAR(1024) NOT NULL,
  `mime_type` VARCHAR(100) NOT NULL,
  `width` INT UNSIGNED NOT NULL DEFAULT 0,
  `height` INT UNSIGNED NOT NULL DEFAULT 0,
  `file_size` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `orientation` SMALLINT NOT NULL DEFAULT 1,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `season` VARCHAR(50) NULL,
  `created` DATETIME NOT NULL,
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `modified` DATETIME NULL,
  `modified_by` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_owner` (`owner_component`,`owner_entity`,`owner_id`),
  KEY `idx_context` (`context_component`,`context_entity`,`context_id`),
  KEY `idx_type` (`photo_type`),
  KEY `idx_status` (`status`),
  KEY `idx_primary` (`is_primary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__xdecarophotos_variants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_id` BIGINT UNSIGNED NOT NULL,
  `preset` VARCHAR(50) NOT NULL,
  `path` VARCHAR(1024) NOT NULL,
  `mime_type` VARCHAR(100) NOT NULL,
  `width` INT UNSIGNED NOT NULL DEFAULT 0,
  `height` INT UNSIGNED NOT NULL DEFAULT 0,
  `crop_x` DECIMAL(10,4) NULL,
  `crop_y` DECIMAL(10,4) NULL,
  `crop_width` DECIMAL(10,4) NULL,
  `crop_height` DECIMAL(10,4) NULL,
  `rotation` SMALLINT NOT NULL DEFAULT 0,
  `generated` DATETIME NOT NULL,
  `checksum` CHAR(64) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_photo_id` (`photo_id`),
  KEY `idx_preset` (`preset`),
  CONSTRAINT `fk_xdecarophotos_variant_photo` FOREIGN KEY (`photo_id`) REFERENCES `#__xdecarophotos_photos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
